[DDP]
world_size = 2   # number of available gpus

[optimizer]
lr = 1e-4

[listener]
listener_sr = 16000

[train_dataloader]
batch_size = 4
num_workers = 0
drop_last = true
pin_memory = true

[validation_dataset]
train_folder = '/data/ssd0/lu.bai/'
shuffle = false
num_tot = 0
wav_len = 0

[validation_dataloader]
batch_size = 1
num_workers = 4
pin_memory = true

[trainer]
epochs = 30
save_checkpoint_interval = 1
clip_grad_norm_value = 3.0
exp_path = '/data/ssd0/lu.bai/exp_wavevnn/'
resume = false
resume_datetime = ''
resume_step = 0
eta = 0.1